### PR TITLE
Add round timer and bomb indicator

### PR DESCRIPTION
**Pull request by nicoeg**
Not sure if the `:timer.send_interval` is the right approach or if a hook would be better?

I've seen some cases where timing is a little bit off. Not sure if this is just caused by delay or...

It's currently not handling match pausing but I've created an issue for this #33

### CODE REVIEW

**Comment by trarbr** [comment]
Well, it's certainly possible to do it this way, but I suggest letting the timer tick on the client (and also determining the color of the timer on the client). The logic that determines which of the possible timeouts is current should live server-side. And it will need some testing, because I'm seeing some bugs but I can't find them in the code right now 😞 One issue is that the timer can tick beyond zero, another is that if the bomb is planted and all the CTs are killed, the bomb icon flashes white and then goes back to red

So what do you think about going back and implementing the timer client side?

**Comment by nicoeg** [comment]
I've implemented the timer with a hook now. I've chosen not to change classes from the hook since we would either have to send a lot of variables to the hook or the whole match.

I am running through the last win to know if the bomb is defused or exploded. We could possibly reverse the order of wins to allow for easy pattern match instead if you like?

I've fixed one of the issues with time where freeze time was not always caught because it was checking phase as well. I am still seeing some issues (sometimes) where one is the timer not always turning red when the bomb is planted.
Is there a reason why `phase` is being checked as well? If not I suggest we remove it from the others too since it'll let the server be able to easier get back when it gets in a bad state.

**Review by trarbr — APPROVED** [review]
> I've implemented the timer with a hook now. I've chosen not to change classes from the hook since we would either have to send a lot of variables to the hook or the whole match.

I think this is great, thanks! 👍 

> I am running through the last win to know if the bomb is defused or exploded. We could possibly reverse the order of wins to allow for easy pattern match instead if you like?

There is also another possibility. We could change the phase from `:round_over` to `{:round_over, reason}` where reason would be one of `:terrorists_win`, `:cts_win`, `:target_bombed`, `:bomb_defused`, `:target_saved`.  And still keep `wins` around for rendering the list of rounds and their result.

> I've fixed one of the issues with time where freeze time was not always caught because it was checking phase as well. I am still seeing some issues (sometimes) where one is the timer not always turning red when the bomb is planted.
> Is there a reason why `phase` is being checked as well? If not I suggest we remove it from the others too since it'll let the server be able to easier get back when it gets in a bad state.

Well, I guess we can remove those checks 😄 This is just what I am used to from implementing other state machines. But if we trust the game to always send the logs in the right order (which is probably safe, given it's transported over HTTP), then I guess we can remove the checks.

The code in `MatchView.ex` makes me want to rewrite part of `Match.ex`. Why keep all the three timeouts around? There's only one timeout at any given time - we never move back from the bomb timeout to round timeout... And then we can rename the `:round` phase to `:round_started` and introduce a `:bomb_planted` state. And then also change the `:round_over` phase as described above. I think that would clean up the code a bit. But you can go ahead and merge this and then I will play around with it when I get some more time.

Good to merge! :shipit:

**Review by trarbr — DISMISSED** [review]
I'm so sorry, but I have been a dork 😢 

When the timer ticks on the client like this, it's only precise if the clock on the client and on the server is in sync, which is probably not a safe assumption. Should we move back to ticking it on the server?

**Comment by trarbr** [comment]
@nicoeg I jumped in and rewrote `Match.ex` as I noted above, and then went back to computing the time left on the server. I think it works OK now (but it probably still has flaws). What do you think?

**Pull request merged**
